# Data
Daily PM2.5 Concentrations All County, 2001-2016
LINK: https://data.cdc.gov/Environmental-Health-Toxicology/Daily-PM2-5-Concentrations-All-County-2001-2016/7vdq-ztk9
This data set is collected by CDC National Environmental Public Health Tracking Network. It provides modeled predictions of PM2.5 levels from the EPA's Downscaler model. Data are at the county level for year 2001-2016. The dataset includes the maximum, median, mean, and population-weighted mean of 24-hour average PM2.5 concentration in μg/m3. This data set is in csv format. It was created on March 25, 2020 and last updated on January 21, 2021. 
Original Data Dimension: 18.2M rows and 8 columns.
Since this dataset is too large, I wouldn't be able to directly download and import from the Centers for Disease Control and Prevention website. Also, to compare with cancer incidence over time, it's better to let both datasets have the same time division (i.e., by year) and same geographical division(i.e., by state), it ensures consistency in the temporal granularity of the data. Thus, I will first group by year and state and aggregate on the PM25_max_pred and PM25_pop_pred columns to make the row number smaller using their query tools and then import using API endpoint. 

Daily County-Level Ozone Concentrations, 2001-2016
LINK: https://data.cdc.gov/Environmental-Health-Toxicology/Daily-County-Level-Ozone-Concentrations-2001-2016/kmf5-t9yc
This data set is collected by CDC National Environmental Public Health Tracking Network. Data are at the county levels for years 2001-2014. The dataset includes the maximum, median, mean, and population-weighted mean estimated 8-hour average ozone concentration in parts per billion (ppb) within 3 meters of the surface of the earth. This data set is in csv format. It was created on March 11, 2020 and last updated on May 21, 2020. 
Original Data Dimension: 18.2M rows and 9 columns
Since the data set is too large, I wouldn't be able to directly download and import from the Centers for Disease Control and Prevention website. For the consistency purpose mentioned above, I will first group by year and state and aggregate on 03_max_pred and O3_pop_pred columns to make the row number smaller using their query tools and then import using API endpoint.


## Description
To answer what geographical areas in the United States have consistently poor air quality and elevated cancer rates. We would perform time series analysis and draw time series line plot. Also, we will use box plot to get a summary of air quality data for multiple regions in a compact format. Each box plot represents a region, and the boxes display the distribution of air quality values (e.g., median, quartiles). Regions with consistently poor air quality will have lower medians and wider interquartile ranges. To double check our finding, we would use heatmap to visualize air quality data across both time and regions. Rows represent regions, columns represent time intervals, and the color scale indicates air quality levels. Consistently poor air quality regions will be represented by darker colors on the heatmap.


## Missing value analysis
```{r}
pm <- read.csv("https://data.cdc.gov/resource/7vdq-ztk9.csv?$query=SELECT%0A%20%20%60year%60%2C%0A%20%20%60statefips%60%2C%0A%20%20max(%60pm25_max_pred%60)%20AS%20%60max_pm25_max_pred%60%2C%0A%20%20avg(%60pm25_pop_pred%60)%20AS%20%60avg_pm25_pop_pred%60%0AGROUP%20BY%20%60year%60%2C%20%60statefips%60")

ozone <- read.csv("https://data.cdc.gov/resource/kmf5-t9yc.csv?$query=SELECT%0A%20%20%60year2%60%2C%0A%20%20%60statefips%60%2C%0A%20%20max(%60o3_max_pred%60)%20AS%20%60max_o3_max_pred%60%2C%0A%20%20avg(%60o3_pop_pred%60)%20AS%20%60avg_o3_pop_pred%60%0AGROUP%20BY%20%60year2%60%2C%20%60statefips%60")
```
